import Head from 'next/head';
import Link from 'next/link';

// mui
import {
  CssBaseline,
  Container,
  Box,
  Button,
  Typography,
  List,
  ListItem,
  ListItemText,
} from '@mui/material';

// components
import Layout from '../src/components/Layout';

export default function Index() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Home - Next.js ToDo App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container className="Home_titles">
          <Typography variant="h1">StuffToDo()</Typography>
          <Typography variant="h2">
            StuffToDo helps you keeping things under control
          </Typography>

          <Box className="btn_callForAction">
            <Link href="/dashboard">
              <Button>Start your first Dashboard</Button>
            </Link>
          </Box>
          <hr />
        </Container>

        <Container className="Home_instructions">
          <Typography variant="h4">
            You do not know how to use it? <br />
            No problem take a look here:
          </Typography>
          <List className="instructions">
            <ListItem>
              <ListItemText>
                Structure your tasks into lists in your head or a piece of paper
              </ListItemText>
            </ListItem>
            <ListItem>
              <ListItemText>
                Give a name to your first list and add it to your dashboard
              </ListItemText>
            </ListItem>
            <ListItem>
              <ListItemText>
                Start adding some tasks to your first list
              </ListItemText>
            </ListItem>
            <ListItem>
              <ListItemText>
                If you want to add more lists you can simply start from step one
                and add more
              </ListItemText>
            </ListItem>
            <ListItem>
              <ListItemText>
                If you make a mistake you can delete lists and tasks by clicking
                on the respective button
              </ListItemText>
            </ListItem>
          </List>
        </Container>
      </Layout>
    </div>
  );
}
