import Head from 'next/head';

// mui
import { Typography } from '@mui/material';

// components
import Layout from '../src/components/Layout';

export default function Index() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Home - Next.js ToDo App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Typography variant="h1">main</Typography>
        </main>
      </Layout>
    </div>
  );
}
